# -*- coding: utf-8 -*-
"""Data analytics task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tIsPWPgHjQr1piCE_QpoWkPBF9-h7n24
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

txt= pd.read_csv (r'/content/drive/MyDrive/Dataset/dataset.txt', delimiter=" ")
df=txt.to_csv(r'/content/dataset.csv', index=None)

data=pd.read_csv('/content/dataset.csv')

data

for i in range(data.shape[1]):
    n_miss = data.iloc[:, i].isnull().sum()
    perc = n_miss / data.shape[0] * 100
    print('> %s, Missing: %d (%.3f%%)' % (data.columns[i], n_miss, perc))

data[data['Province_State']==0]

data.dtypes

data.head(20)

data['Date'].fillna(method='ffill', inplace=True)

data['Confirmed'].fillna(0, inplace=True)
data['Deaths'].fillna(0, inplace=True)

for i in range(data.shape[1]):
    n_miss = data.iloc[:, i].isnull().sum()
    perc = n_miss / data.shape[0] * 100
    print('> %s, Missing: %d (%.3f%%)' % (data.columns[i], n_miss, perc))

data

processeddata=data.to_csv(r'preprocessed_dataset.csv', index=None)

plt.bar(data['Deaths'],data['Confirmed'])
plt.show()